# Configuration of Smarttren
# Documentation: https://docs.mitrapaytren.net
# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.

baseurl = "/"
title = "Web Support Resmi Mitra PayTren"
languageCode = "id"
theme = "smarttren"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 8

[permalinks]
  post = "/:slug/"
  pages = "/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
  
[taxonomies]
  tag = "tags"
  category = "categories"
  product = "product"
  featured = "featured"

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

[params]

  # Date and time format (refer to Go's date format: http://fuckinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Jan 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "3:04 PM"

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to Go's date format: http://fuckinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# Main Menu

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/store/"
    name = "Store"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Artikel"
    weight = 3
[[menu.main]]
    url = "/marketing-plan/"
    name = "Marketing Plan"
    weight = 4
    
# Footer Menu

[[menu.footer]]
    url = "/"
    name = "Home"
    weight = 1
    
[[menu.footer]]
    url = "/store"
    name = "Store"
    weight = 2

[[menu.footer]]
    url = "/tentang-kami/"
    name = "Tentang kami"
    weight = 3

[[menu.footer]]
    url = "/hubungi-kami/"
    name = "Hubungi Kami"
    weight = 4
    
# Store Menu

[[menu.store]]
    url = "/"
    name = "Home"
    weight = 1
    
[[menu.store]]
    url = "/product/dress/"
    name = "Dress"
    weight = 2
    
[[menu.store]]
    url = "/product/hijab/"
    name = "Hijab"
    weight = 3

[[menu.store]]
    url = "/product/"
    name = "Produk"
    weight = 4

[[menu.store]]
    url = "/hubungi-kami/"
    name = "Hubungi Kami"
    weight = 5